version: '3'
services:
  nodejs:
    image: nodejs
    container_name: nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "80:80"
